export enum RouterLink {
  Landing = '',
  InterviewRevision = '/interview-revision',
  InterviewQuestionDetail = '/interview-question-detail/:id',
  MockInterview = '/mock-interview',
  MockInterviewDetail = '/mock-interview-detail/:id',
  MockInterviewResult = '/mock-interview-result/:id',
  TrendNews = '/trend-news',
  TrendNewsDetail = '/trend-news-detail/:id',
  RecruitmentNews = '/recruitment-news',
  RecruitmentNewsDetail = '/recruitment-news-detail/:id',
  CommunityDiscussion = '/community-discussion',
  CommunityDiscussionDetail = '/community-discussion-details/:id',
  About = '/about-abc-interview-support',
}
